pitt-crc/wrappers

README.md
Fixes a minor issue raised by the codacy inspection tool
=> Removes dollar signs from shell prompt examples

_base_parser.py, crc-quota.py
This PR introduces incremental improvements to the `crc-quota` utility. There are still a large number of QA inspections that have not been addressed. However, it is a step in the right direction.
=> Refactor crc-quota to use new base parser

crc-interactive.py, crc-sus.py
Refactores crc-interactive to use BaseParser class and addresses various QA inspections.
=> Refactores crc-interactive to use BaseParser class

.coveragrc, .github/workflows/Unittests.yml, .gitignore, README.md, _base_parser.py, crc-scancel.py, requirements.txt, tests/test_crc_sus.py
We don't have any tests yet so I've added a small example as a placeholder. Having a CI action in place will help make sure we are running tests as we write them.
=> Add github action for running tests

crc-squeue.py, tests/test_crc_squeue.py, tests/test_crc_sus.py
Writes some tests for the creation of slurm commands in `crc-squeue.py`
=> Add tests for crc-squeue

crc-interactive.py, crc-scancel.py, crc-scontrol.py, tests/test_crc_interactive.py, tests/test_crc_proposal_end.py, tests/test_crc_scancel.py, tests/test_crc_scontrol.py
I had some free time today so I started adding a few tests to the test suite.
=> Partial progress on building out test suite

apps/__init__.py, apps/base_parser.py, apps/crc_idle.py, apps/crc_usage.pl, setup.py
Fixes a few typos in `setup.py` and updates the package docstring.
I'm not able to continue development again until Monday. I wanted to make sure these changes were available before then.
=> Fix install bugs and add package docs

apps/__init__.py, apps/crc_idle.py, apps/crc_interactive.py, apps/crc_job_stats.py, apps/crc_proposal_end.py, apps/crc_quota.py, apps/crc_scancel.py, apps/crc_scontrol.py, apps/crc_show_config.py, apps/crc_sinfo.py, apps/crc_squeue.py, apps/crc_sus.py, apps/crc_usage.py
Editing pass for the command line docstring exposed to users.
=> Command line docstring pass

apps/system_info.py, tests/test_shell.py
=> Decode returns from Shell commands

apps/_base_parser.py
=> Add multiline doc support

.github/workflows/Unittests.yml, setup.py
=> Add package installation to testing workflow

.github/workflows/DeployDocs.yml, .github/workflows/TestDocs.yml, .github/workflows/Unittests.yml, apps/_system_info.py, setup.py
Adds support for the following installation options:
```bash
pip install .[docs]
pip install .[tests]
```
=> Add pip extras for docs and tests

apps/__init__.py, docs/source/conf.py, pyproject.toml
Updates the version to `0.4.1` and drops outdated meta data from the init file.
=> Patch version bump

.github/dependabot.yml
- Add GitHub Actions to dependabot
- Increase PR limit
- Increase PR frequency to weekly
=> Expand dependabot scope

apps/_system_info.py, apps/crc_idle.py, apps/crc_interactive.py
Quick linting pass on application source code.
=> Auto PEP8 linting

.github/actions/build-sphinx/action.yml, .github/actions/run-tests/action.yml, .github/workflows/DocumentationBuild.yml, .github/workflows/DocumentationPublish.yml, .github/workflows/PackagePublish.yml, .github/workflows/PackageTest.yml
I'm rolling out some new CI architectures to various projects. The developer workflow remains unchanged. However, the new CI has some useful improvements:
1. CI workflows switch from reusable workflows to composite actions. This makes the visual CI dashboard cleaner and easier to read.
1. A dedicated job for test suite branch protections is added. This fixes a bug where branches sometimes auto merge even when tests fail.
=> Updates CI

apps/utils/system_info.py, tests/test_crc_usage.py
Adds basic test coverage for the `crc-usage` application.
=> Adds tests for crc_usage.py

apps/crc_sinfo.py, tests/test_crc_sinfo.py
Also adds previously missing test coverage for the application.
=> Adds -z and -c arguments to crc-sinfo

apps/crc_interactive.py, apps/crc_show_config.py, apps/crc_sus.py, apps/utils/cli.py, tests/test_crc_show_config.py, tests/test_crc_squeue.py, tests/test_crc_usage.py, tests/utils/cli/test_base_parser.py
=> Drops x11 supprt from crc-interactive

apps/crc_interactive.py, apps/crc_proposal_end.py, apps/crc_sus.py, apps/crc_usage.py, pyproject.toml, tests/test_crc_sus.py
So far I have updated the `pyproject.toml` to include `crc-bank` as a dependency, and with that I noticed an incompatibility with `dataset`'s sqlalchemy version requirements. 
I've started to refactor the code for `crc_sus.py`, `crc_usage.py`, and `crc_proposal_end.py` accordingly.
=> Update Wrappers to utilize New CRC Bank Code

apps/crc_interactive.py
Set default time to 1 hour instead of 1 minute
=> Update default time in crc_interactive.py

apps/crc_proposal_end.py, apps/crc_sus.py, apps/crc_usage.py, apps/utils/keystone.py
=> crc-proposal-end

apps/crc_sus.py, apps/crc_usage.py, apps/utils/keystone.py
=> Gather enabled clusters from keystone instead of using hardcoded variable

apps/crc_proposal_end.py, apps/crc_sus.py, apps/crc_usage.py, apps/utils/keystone.py
This PR addresses #242 
I've tested each of the changed wrappers out on the cluster and they appear to work properly
=> Update the utilities and relevant wrappers to user the KeystoneApi Client Class

apps/crc_idle.py, tests/test_crc_idle.py
Adding the min max memory calculation to crc-idle and its tests.
=> CRCIdle - adding min-max memory

apps/crc_proposal_end.py, apps/crc_sus.py, apps/crc_usage.py, apps/utils/keystone.py, pyproject.toml
Compatibility update for Keystone version 0.5.0
=> Upgrade wrappers to use teams instead of groups
