pitt-crc/wrappers

crc-proposal-end.py
crc-squeue.py
crc-sus.py

- Refactors crc-proposal-end.py to use the `BaseParser` parent class.
- Addresses code quality inspections

Refactors crc-proposal-end to use base parser

---

_base_parser.py
crc-scancel.py
crc-sinfo.py
crc-squeue.py

By necessity, wrapper scripts need to pipe commands to the underlying shell. However, piping shell commands introduce security vulnerabilities.
This PR introduces a dedicated method to the base parser (`BaseParser.run_command`) for executing shell commands. This isn't inherently safer except it ensures consistency in how shell commands are run. If we do decide to improve security (somehow), we will only need to make changes in one place.
This change also decreases the number of security warnings from the QA tool which is nice.

Introduce dedicated method for running shell commands

---

_base_parser.py
crc-idle.py
crc-proposal-end.py
crc-scancel.py
crc-scontrol.py
crc-sus.py

Resolves #16 
This PR adds the `mpi` partition to the `mpi` cluster. Instead of making changes to multiple hardcoded values, I moved common application settings into a `CommonSettings` class.

Moves duplicate, hardcoded settings into dedicated class

---

_base_parser.py
crc-interactive.py

- Default values for `crc-interactive` are now set in the help text dynamically
- Fixed a bug where the default number of nodes was set incorrectly from application-level settings
- Arguments for `crc-interactive` are now grouped together by category in the help text.
- The width of the help text has been increased for all apps to ensure easier readability

Improves formatting of crc-interactive help text

---

crc-scancel.py
tests/test_crc_scancel.py

I've done a refactoring pass on `crc-scancel` to better align methods with the SRP. Not a big change, but it's a small step toward better test coverage and maintainability.

Simplify crc-scancel app

---

README.md
_base_parser.py
crc-idle.py
crc-interactive.py
crc-job-stats.py
crc-scancel.py
crc-scontrol.py
crc-sus.py
tests/test_crc_quota.py
tests/test_crc_scontrol.py

Upcoming maintenance will retire some of the cluster partitions. We've had trouble in the past with keeping hardcoded partition names up to date. This PR determines partition names dynamically.

Determines cluster partition names dynamically

---

crc-idle.py

I don't think #14 fully resolved #6, as GPUs from gpu-stage08 still show as usable by crc-idle.
This adds an additional output format item to the sinfo call to report host node state, and then if the state is drain, sets the number of idle GPUs to zero. 
Not an issue for the other clusters, as drain state CPU A/I/O/T reports idle as 0.
I'm pretty slurm does not allocate jobs on nodes in the drain state, so this will prevent confusion there.

Add logic to GPU counting to account for drain state

---

apps/__init__.py
docs/source/conf.py
docs/source/templates/python/module.rst

- Fixed error where the example for editing `setup.py` does not render
- Adds a custom template for module documentation that creates cleaner rendered documentation
- Enables the Napolean extension so google style docs render correctly.

Formatting updates to rendered HTML docs

---

setup.py

Modern type hints are not supported in Python 3.6

Require Python >= 3.7 in setup.py

---

apps/crc_proposal_end.py
apps/crc_sus.py

WAL is enabled in the `dataset` package by default. This causes problems when working against sqlite DBs that are read only.

Disable WAL for DB queries

---

apps/crc_scancel.py

Switches out `stdout.write` for the built-in `print` function

Fix bug where ./crc-scancel hangs waiting for input

---

apps/__init__.py
docs/source/conf.py

Uses package metadata from the application __init__ file when building the docs.
I've included the author, version, and copyright

Fetch package meta dynamically when building docs

---

apps/crc_squeue.py

Had some tickets come in where users were confused by the reason that their jobs were not running. The wrapper script truncates the output of the 'reason' field to be too short to convey that there was a reservation for maintenance.

Increase Length of squeue node availability reason

---

pyproject.toml

I'm pinning the license version at GPL v3. I don't see an immediate need to support the "or later" option.

Updates packaging file with license information

---

apps/crc_interactive.py

Enabled specification of both %H:%M format as well as integer hours for allocated time. The time argument is now treated as a string instead of an integer. Addresses issue #158.

Update time format for crc-interactive

---

apps/crc_idle.py
apps/crc_interactive.py
apps/crc_scancel.py
apps/crc_show_config.py
apps/crc_sus.py
apps/crc_usage.py
apps/utils/cli.py
apps/utils/system_info.py
tests/test_crc_idle.py
tests/test_crc_show_config.py
tests/utils/cli/test_commandline_application.py

Two major changes:
The ``CommandlineApplication.app_interface`` method is no longer a factory method. Instead it mutates a parser argument. This forces child classes to use the automatically provided parser (or explicitly override the default in the `__init__` method).
`SlurmInfo` has been renamed to `Slurm`.

Updates signatures for utiliy classes

---

apps/__init__.py

The package name was incorrect in `__init__.py`. This prevented the package from finding the correct version number.

Fixes bug where --version gives 0.0.0

---

apps/crc_proposal_end.py
apps/crc_sus.py
apps/crc_usage.py
pyproject.toml
tests/test_crc_sus.py

This reverts commit de647a3aeb7af230ee746530c98f367c88488276.
It looks like the banking code was incorporated into main prematurely and is causing issues in production.

Revert "Update Wrappers to utilize New CRC Bank Code (#195)"

---

apps/crc_interactive.py

It seems when entering the decimal value for the parameter "-t" or "--time" in crc-interactive it's formatted in the srun_dict as "{}:00" which makes it interpreted as "MM:SS" but if using the string format "01:00" and it's formatted in the srun_dict as "{}:00" then it's interpreted as "HH:MM:SS" which is the necessary format for "srun". I added a possible fix, please take a look and feel free to discard it and fix it in any other way because I am sure this is not the best way to fix it, I was just trying to expose where the error comes from.

HH:MM:SS time formatting bug in crc-interactive

---

apps/crc_interactive.py
tests/test_crc_interactive.py

Adds test coverage for the `parse_time` method.

Adds tests for time parsing in crc-interactive

---

apps/crc_proposal_end.py
apps/crc_sus.py
apps/crc_usage.py
apps/utils/keystone.py

This PR also ensures the wrappers are using the more advanced query parameters enabled by [Pitt-crc/keystone-api#](https://github.com/pitt-crc/keystone-api/pull/280)

Show most recently expired allocation info when there are no active allocations

---

apps/utils/keystone.py

Currently, the start date provided to sreport is just the earliest start date across a group's active allocations. This is not necessarily accurate as the usage value being compared against the limits is the usage since the last raw usage reset. 
This PR take the rawusage reset date into consideration, by returning the max of the earliest start date found and the most recent raw usage reset date. We want the max because start dates found prior to the raw usage reset date are what's creating the possibility of > 100% usage in the crc-usage output.
I tested this works properly on the cluster, and that it does not break `crc-sus`.
Before:
```
+-----------------------------------------------------------------------------+
|              Resource Allocation Request Information for 'slee' …
```

Take Rawusage reset date into account when determining start date for `sreport` calls

---

apps/crc_proposal_end.py
apps/crc_sus.py
apps/crc_usage.py
apps/utils/keystone.py
pyproject.toml

This PR makes the changes necessary to use `keystone-api-client` instead of the `KeystoneApi` class under `apps.utils.keystone`. Testing this on the cluster will require that [these fixes to url handling](https://github.com/pitt-crc/keystone-python-client/pull/19) are present in the latest deployment of keytstone-python-client. I will make sure to adjust the version in the `pyproject.toml` here when that is the case.

Incorporate keystone-api-client package  

---

apps/crc_idle.py
apps/utils/__init__.py
tests/test_crc_idle.py

Adds unit tests with improved test coverage for crc-idle. I'm mocking the number of idle resources returned by Slurm. This means the tests are limited in their ability to identify compatibility problems with Slurm. However, I don't see an easy way to set up idle resources in the test environment.

Increase test coverage for crc-idle

---

apps/crc_interactive.py
tests/test_crc_interactive.py

Adds test coverage for argument validation and for the creation of `srun` commands.

Increase testing coverage for crc-interactive

---

apps/crc_interactive.py

Adding srun's gres parameter handling logic for teach in order to pass the requested gres and set the default num_gpus if not requested when c=teach and p=gpu

Adding gres handling for teach

---

apps/crc_proposal_end.py
apps/crc_sus.py
apps/crc_usage.py

Closes #262 
Looks like a mismatch between the expected and returned type of `get_most_recent_expired_request`.
@Comeani can you double check this works for you?

Treat expired requests as list to fix indexing error

---

apps/crc_idle.py
tests/test_crc_idle.py

This is a minor fix and it can wait for the next release whenever this will come out. I fixed it on the cluster anyway and it's working normally.

Fix crc-idle casting issue for free memory when gpu resource is in drain state

---

apps/crc_idle.py
tests/test_crc_idle.py

Fixing crc-idle when nodes are in down or drain status for CPU resources. I added the "%t" option for the resource status in the sinfo command used and conditioned the parsing of the parsing of idle resources based on that.

Fixing crc-idle for down CPU resources

---

apps/crc_idle.py
tests/test_crc_idle.py

It wasn't implemented in the wrapper anyway.

Removing Invest as a cluster option from crc-idle and tests
